// @title DJJS Event Reporting API
// @version 1.0
// @description API documentation for the DJJS Event Reporting Backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email vaish@gmail.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// @host localhost:8080
// @BasePath /
package main

import (
	"log"
	"os"
	"time"

	"github.com/followCode/djjs-event-reporting-backend/app/api"
	"github.com/followCode/djjs-event-reporting-backend/app/middleware"
	"github.com/followCode/djjs-event-reporting-backend/app/services"
	"github.com/followCode/djjs-event-reporting-backend/config"
	"github.com/gin-contrib/cors"
	"github.com/joho/godotenv"

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "github.com/followCode/djjs-event-reporting-backend/docs" // docs is generated by Swag CLI
)

func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found, using system env variables")
	}

	// 1️⃣ Connect to Postgres
	config.ConnectDB()

	// 2️⃣ Set JWT secret from environment
	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		log.Fatal("JWT_SECRET is missing in .env")
	}
	config.JWTSecret = []byte(jwtSecret)

	// 3️⃣ Initialize S3
	if err := services.InitializeS3(); err != nil {
		log.Printf("Warning: Failed to initialize S3: %v", err)
	} else {
		log.Println("S3 initialized successfully")
	}

	// 4️⃣ Create Gin router
	r := gin.Default()

	// Enable CORS for Angular frontend
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"*"},
		ExposeHeaders:    []string{"Content-Length", "Authorization"},
		AllowCredentials: false, // must be false if AllowOrigins = "*"
		MaxAge:           12 * time.Hour,
	}))

	// Swagger documentation route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// 5️⃣ Setup all API routes
	api.SetupRoutes(r)

	// 6️⃣ Protected route example
	r.GET("/protected", middleware.AuthMiddleware(), func(c *gin.Context) {
		userID, _ := c.Get("userID")
		roleID, _ := c.Get("roleID")
		c.JSON(200, gin.H{
			"message": "You are authorized",
			"userID":  userID,
			"roleID":  roleID,
		})
	})

	// 7️⃣ Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port %s...", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}

